"""Diagnostic report domain entity — the AI-generated (placeholder) output
tied to a sample. Always carries the research-use disclaimer and a
confidence score; never a bare unqualified diagnosis."""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any
from uuid import UUID, uuid4

RESEARCH_DISCLAIMER = (
    "This report was generated by a research-prototype AI model using "
    "synthetic and/or unvalidated data. It is NOT a medical diagnosis and "
    "must NOT be used for clinical decision-making without independent "
    "validation and regulatory clearance."
)


@dataclass
class DiagnosticReport:
    sample_id: UUID
    model_name: str
    model_version: str
    findings: dict[str, Any]  # e.g. {"glucose_mg_dl": 132, "flag": "elevated"}
    confidence_scores: dict[str, float]  # per-finding confidence, 0-1
    generated_by: UUID | None = None  # user id if human-reviewed / triggered
    disclaimer: str = RESEARCH_DISCLAIMER
    reviewed: bool = False
    reviewed_by: UUID | None = None
    id: UUID = field(default_factory=uuid4)
    created_at: datetime = field(default_factory=datetime.utcnow)
