from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.domain.entities.patient import Patient


class PatientRepository(Protocol):
    async def create(self, patient: Patient) -> Patient: ...
    async def get_by_id(self, patient_id: UUID) -> Patient | None: ...
    async def get_by_mrn(self, mrn: str) -> Patient | None: ...
    async def list(self, skip: int = 0, limit: int = 50, search: str | None = None) -> list[Patient]: ...
    async def update(self, patient: Patient) -> Patient: ...
    async def delete(self, patient_id: UUID) -> None: ...
