from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.domain.entities.report import DiagnosticReport


class ReportRepository(Protocol):
    async def create(self, report: DiagnosticReport) -> DiagnosticReport: ...
    async def get_by_id(self, report_id: UUID) -> DiagnosticReport | None: ...
    async def list_by_sample(self, sample_id: UUID) -> list[DiagnosticReport]: ...
    async def list(self, skip: int = 0, limit: int = 50) -> list[DiagnosticReport]: ...
    async def update(self, report: DiagnosticReport) -> DiagnosticReport: ...
