from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.domain.entities.sample import Sample


class SampleRepository(Protocol):
    async def create(self, sample: Sample) -> Sample: ...
    async def get_by_id(self, sample_id: UUID) -> Sample | None: ...
    async def get_by_barcode(self, barcode: str) -> Sample | None: ...
    async def list_by_patient(self, patient_id: UUID) -> list[Sample]: ...
    async def list(self, skip: int = 0, limit: int = 50) -> list[Sample]: ...
    async def update(self, sample: Sample) -> Sample: ...
