"""Abstract repository interface for User — the application/domain layers
depend on this Protocol, never on SQLAlchemy directly (Dependency Inversion)."""
from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.domain.entities.user import User


class UserRepository(Protocol):
    async def create(self, user: User) -> User: ...
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def list(self, skip: int = 0, limit: int = 50) -> list[User]: ...
    async def update(self, user: User) -> User: ...
    async def delete(self, user_id: UUID) -> None: ...
