input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
    skip_on_invalid_json => true
  }
}

output {
  opensearch {
    hosts => ["${OPENSEARCH_HOST}"]
    index => "equidx-logs-%{+YYYY.MM.dd}"
    ssl_certificate_verification => false
  }
}
