"use client";

import { useEffect, useState } from "react";
import DashboardShell from "../../components/DashboardShell";
import { api } from "@/lib/api-client";

interface Report {
  id: string;
  model_name: string;
  model_version: string;
  findings: Record<string, unknown>;
  confidence_scores: Record<string, number>;
  disclaimer: string;
  reviewed: boolean;
}

export default function ReportsPage() {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  useEffect(() => {
    const token = typeof window !== "undefined" ? localStorage.getItem("equidx_access_token") ?? undefined : undefined;
    // Demo: there's no "list all reports" endpoint by design (reports are
    // fetched per-sample) — in a full build this page would let you pick a
    // sample first. Left here to show the report card UI/shape.
    setLoading(false);
    if (!token) setErrorMsg("Sign in, then generate a report from a sample's detail view.");
  }, []);

  return (
    <DashboardShell>
      <h1 className="font-display text-2xl text-mist-100">Diagnostic Reports</h1>
      <p className="mt-1 max-w-2xl text-sm text-mist-500">
        Every report is generated by a placeholder AI model trained on
        synthetic data and carries a confidence score per finding, plus the
        research-use disclaimer below.
      </p>

      {errorMsg && <p className="mt-6 text-sm text-amber-400">{errorMsg}</p>}

      <div className="mt-6 grid gap-4 md:grid-cols-2">
        {reports.map((r) => (
          <div key={r.id} className="rounded-xl border border-ink-700 p-5">
            <div className="flex items-center justify-between">
              <p className="font-mono text-xs text-signal-500">{r.model_name} · v{r.model_version}</p>
              <span className={`text-xs ${r.reviewed ? "text-signal-400" : "text-amber-400"}`}>
                {r.reviewed ? "Reviewed" : "Pending review"}
              </span>
            </div>
            <dl className="mt-3 space-y-1 text-sm">
              {Object.entries(r.findings).map(([k, v]) => (
                <div key={k} className="flex justify-between text-mist-300">
                  <dt className="capitalize">{k.replace(/_/g, " ")}</dt>
                  <dd className="text-mist-100">{String(v)}</dd>
                </div>
              ))}
            </dl>
            <p className="mt-4 border-t border-ink-700 pt-3 text-xs text-mist-500">{r.disclaimer}</p>
          </div>
        ))}
      </div>
      {loading && <p className="mt-6 text-sm text-mist-500">Loading…</p>}
    </DashboardShell>
  );
}
