"use client";

import DashboardShell from "../../components/DashboardShell";

export default function ReportsPage() {
  return (
    <DashboardShell>
      <h1 className="font-display text-2xl text-mist-100">Diagnostic Reports</h1>
      <p className="mt-1 max-w-2xl text-sm text-mist-500">
        Every report is generated by a placeholder AI model trained on
        synthetic data and carries a confidence score per finding, plus the
        research-use disclaimer below.
      </p>

      <div className="mt-6 rounded-xl border border-ink-700 p-5 text-sm text-mist-400">
        Reports are retrieved per sample. Open a sample detail view to generate
        or review its research-prototype report.
      </div>
    </DashboardShell>
  );
}
