"""
EQUIDX AI — Backend API entrypoint.

RESEARCH PROTOTYPE — NOT FOR CLINICAL USE. See README.md and
docs/docs/disclaimer.md.
"""
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from prometheus_fastapi_instrumentator import Instrumentator
from starlette.middleware.sessions import SessionMiddleware
from strawberry.fastapi import GraphQLRouter

from app.api.v1.error_handlers import register_error_handlers
from app.api.v1.router import api_router
from app.core.config import get_settings
from app.core.logging import configure_logging, get_logger
from app.graphql.context import get_graphql_context
from app.graphql.schema import schema
from app.middleware.audit import RequestLoggingMiddleware

settings = get_settings()
configure_logging(settings.LOG_LEVEL)
logger = get_logger("startup")


@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("equidx_backend_starting", environment=settings.ENVIRONMENT)
    yield
    logger.info("equidx_backend_shutdown")


app = FastAPI(
    title=settings.PROJECT_NAME,
    description=(
        "EQUIDX AI research/prototype backend API. NOT a medical device. "
        "All diagnostic output is generated by placeholder AI models trained "
        "on synthetic data and is for demonstration purposes only."
    ),
    version="0.1.0",
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_url="/openapi.json",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
app.add_middleware(SessionMiddleware, secret_key=settings.SECRET_KEY)
app.add_middleware(RequestLoggingMiddleware)

register_error_handlers(app)

app.include_router(api_router, prefix=settings.API_V1_PREFIX)

graphql_app = GraphQLRouter(schema, context_getter=get_graphql_context)
app.include_router(graphql_app, prefix="/graphql")

Instrumentator().instrument(app).expose(app, endpoint="/metrics")


@app.get("/health", tags=["Health"])
async def health():
    return {"status": "ok", "service": "equidx-backend", "disclaimer": "research prototype — not for clinical use"}


@app.get("/", tags=["Health"])
async def root():
    return {
        "service": "EQUIDX AI Backend",
        "version": "0.1.0",
        "docs": "/docs",
        "graphql": "/graphql",
        "disclaimer": "Research prototype. Not a medical device. Not for clinical use.",
    }
